services:
  euf_summariser:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/pranavnbapat/euf_summariser:latest
    container_name: euf_summariser
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
